apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: app
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: otel:4317
      isSecure: false
      protocol: grpc