apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pub-sub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://guest:guest@localhost:5672"
  - name: durable
    value: true
  - name: exchangeKind
    value: topic
  - name: deletedWhenUnused
    value: false 
  - name: autoAck
    value: false
  - name: deliveryMode
    value: 2 
  - name: publisherConfirm
    value: true
  - name: requeueInFailure
    value: true
  - name: prefetchCount
    value: 4