name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dapr CLI
        run: |
          wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
          dapr init
      - name: Install dev certificates
        run: |
          # Required for linux agents https://github.com/dotnet/aspire/discussions/4546
          dotnet tool update -g linux-dev-certs
          dotnet linux-dev-certs install

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x' 
      
      - name: Run tests
        run: |
          dotnet test ./AspireMigrationExample.sln --configuration Release
          
      - name: Docker container status
        if: ${{ always() }}
        run: docker compose -f docker-compose.yml ps

      - name: Docker container logs
        if: ${{ always() }}
        run: docker compose -f docker-compose.yml logs

# As an example, pushing the images:
#  push:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Login to Docker Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ vars.DOCKER_REGISTRY }}
#          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
#          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
#
#      - name: Build and push apigateway service
#        run: |
#          docker compose build apigateway
#          docker tag apigateway:latest ${{ vars.DOCKER_REGISTRY }}/apigateway:${VERSION}
#          docker push ${{ vars.DOCKER_REGISTRY }}/apigateway:${VERSION}
#          
#      - name: Build and push catalog service
#        run: |
#          docker compose build catalogservice
#          docker tag catalogservice:latest ${{ vars.DOCKER_REGISTRY }}/catalogservice:${VERSION}
#          docker push ${{ vars.DOCKER_REGISTRY }}/catalogservice:${VERSION}